### PR TITLE
Improved MIDI Keyboard

### LINKED ISSUE #74: Improve MIDI Piano Roll

### PR DESCRIPTION
**Pull request by fde31**
closes #74

### CODE REVIEW

**Comment by x37v** [comment]
looking nice but would be real great if we got an octave on mobile

image

**Comment by fde31** [comment]
k adjusted a few things incl. considering `dvh` instead of `vh` to ensure the correct keyboard sizing

**Review by x37v — APPROVED** [review]
I can't test it where I am but I trust that you got it!

**Comment by fde31** [comment]
haha u are a brave soul :)

**Pull request merged**
